//! StreamZero artifact generator.
//!
//! Runs the (deterministic) trusted setup once and writes:
//!   - `artifacts/proving_key.bin`   — embedded by the wasm prover
//!   - `artifacts/verifying_key.json`— hex of the VK, reference for deployment
//!   - the contract's `e2e_fixtures.rs` — a real proof for the on-chain test,
//!     produced with the SAME keys, so "tested VK" == "deployed VK".
//!
//! Run: `cargo run --release` from this directory.

use ark_serialize::CanonicalSerialize;
use std::fmt::Write as _;
use std::fs;
use streamzero_prover as sz;

const RECIPIENT_STRKEY: &str = "GDBB5HXDWOJVTZEKYXRCQIKKPMCWSO73RMTOZMRVRQ55T7AEEREFREI3";
const SECRET: u64 = 42;
const SALARY_RATE: u64 = 10;
const START_TIME: u64 = 1000;
const CURRENT_TIME: u64 = 1100; // 100s elapsed -> 1000 vested
const WITHDRAW_AMOUNT: u64 = 400;
const ALREADY_WITHDRAWN: u64 = 0;

fn arr_lit(bytes: &[u8]) -> String {
    let mut s = String::from("[");
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        write!(s, "0x{:02x}", b).unwrap();
    }
    s.push(']');
    s
}

fn main() {
    let cfg = sz::poseidon_config();

    // 1. Deterministic setup -> persist keys.
    let (pk, vk) = sz::setup();
    fs::create_dir_all("artifacts").unwrap();
    {
        let mut buf = Vec::new();
        pk.serialize_compressed(&mut buf).unwrap();
        fs::write("artifacts/proving_key.bin", &buf).unwrap();
        println!("wrote artifacts/proving_key.bin ({} bytes)", buf.len());
    }
    let evk = sz::encode_vk(&vk);
    {
        let mut j = String::from("{\n");
        writeln!(j, "  \"alpha\": \"{}\",", hex::encode(evk.alpha)).unwrap();
        writeln!(j, "  \"beta\": \"{}\",", hex::encode(evk.beta)).unwrap();
        writeln!(j, "  \"gamma\": \"{}\",", hex::encode(evk.gamma)).unwrap();
        writeln!(j, "  \"delta\": \"{}\",", hex::encode(evk.delta)).unwrap();
        j.push_str("  \"ic\": [\n");
        for (i, p) in evk.ic.iter().enumerate() {
            let comma = if i + 1 < evk.ic.len() { "," } else { "" };
            writeln!(j, "    \"{}\"{}", hex::encode(p), comma).unwrap();
        }
        j.push_str("  ]\n}\n");
        fs::write("artifacts/verifying_key.json", j).unwrap();
        println!("wrote artifacts/verifying_key.json (ic len {})", evk.ic.len());
    }

    // 2. Prove the demo scenario with the same keys -> e2e fixtures.
    let mut secret_be = [0u8; 32];
    secret_be[24..].copy_from_slice(&SECRET.to_be_bytes());
    let secret = sz::fr_from_be_bytes(&secret_be);
    let recipient = sz::recipient_field(RECIPIENT_STRKEY);
    let w = sz::Witness {
        secret,
        salary_rate: SALARY_RATE,
        start_time: START_TIME,
        current_time: CURRENT_TIME,
        withdraw_amount: WITHDRAW_AMOUNT,
        already_withdrawn: ALREADY_WITHDRAWN,
        recipient,
    };
    let proof = sz::prove(&pk, &w);
    let pubs = w.public_inputs(&cfg);
    assert!(sz::verify(&vk, &pubs, &proof), "native verify failed");
    println!("native Groth16 verify: OK ({} public inputs)", pubs.len());

    let ep = sz::encode_proof(&proof);
    let commitment = sz::fr_be(&pubs[0]);
    let nullifier = sz::fr_be(&pubs[3]);

    let mut out = String::new();
    out.push_str("// @generated by streamzero-prover — DO NOT EDIT.\n");
    out.push_str("// Real Groth16/BN254 proof for the StreamZero statement, encoded in the\n");
    out.push_str("// Soroban host byte layout. Regenerate via `cargo run` in proving/streamzero-prover.\n\n");
    writeln!(out, "pub const RECIPIENT_STRKEY: &str = \"{RECIPIENT_STRKEY}\";").unwrap();
    writeln!(out, "pub const CURRENT_TIME: u64 = {CURRENT_TIME};").unwrap();
    writeln!(out, "pub const WITHDRAW_AMOUNT: u64 = {WITHDRAW_AMOUNT};").unwrap();
    writeln!(out, "pub const ALREADY_WITHDRAWN: u64 = {ALREADY_WITHDRAWN};\n").unwrap();
    writeln!(out, "pub const COMMITMENT: [u8; 32] = {};", arr_lit(&commitment)).unwrap();
    writeln!(out, "pub const NULLIFIER: [u8; 32] = {};\n", arr_lit(&nullifier)).unwrap();
    writeln!(out, "pub const VK_ALPHA: [u8; 64] = {};", arr_lit(&evk.alpha)).unwrap();
    writeln!(out, "pub const VK_BETA: [u8; 128] = {};", arr_lit(&evk.beta)).unwrap();
    writeln!(out, "pub const VK_GAMMA: [u8; 128] = {};", arr_lit(&evk.gamma)).unwrap();
    writeln!(out, "pub const VK_DELTA: [u8; 128] = {};", arr_lit(&evk.delta)).unwrap();
    writeln!(out, "pub const VK_IC: [[u8; 64]; {}] = [", evk.ic.len()).unwrap();
    for p in &evk.ic {
        writeln!(out, "    {},", arr_lit(p)).unwrap();
    }
    out.push_str("];\n\n");
    writeln!(out, "pub const PROOF_A: [u8; 64] = {};", arr_lit(&ep.a)).unwrap();
    writeln!(out, "pub const PROOF_B: [u8; 128] = {};", arr_lit(&ep.b)).unwrap();
    writeln!(out, "pub const PROOF_C: [u8; 64] = {};", arr_lit(&ep.c)).unwrap();

    let dest = "../../streamzero-contract/contracts/streamzero/src/e2e_fixtures.rs";
    fs::write(dest, out).unwrap();
    println!("wrote fixtures -> {dest}");

    // JSON mirror of the demo proof: inputs + expected outputs, so the wasm
    // path can be cross-checked for byte-identical output.
    let mut j = String::from("{\n");
    writeln!(j, "  \"secret_hex\": \"{}\",", hex::encode(secret_be)).unwrap();
    writeln!(j, "  \"salary_rate\": {SALARY_RATE},").unwrap();
    writeln!(j, "  \"start_time\": {START_TIME},").unwrap();
    writeln!(j, "  \"current_time\": {CURRENT_TIME},").unwrap();
    writeln!(j, "  \"withdraw_amount\": {WITHDRAW_AMOUNT},").unwrap();
    writeln!(j, "  \"already_withdrawn\": {ALREADY_WITHDRAWN},").unwrap();
    writeln!(j, "  \"recipient_strkey\": \"{RECIPIENT_STRKEY}\",").unwrap();
    writeln!(j, "  \"commitment\": \"{}\",", hex::encode(commitment)).unwrap();
    writeln!(j, "  \"nullifier\": \"{}\",", hex::encode(nullifier)).unwrap();
    writeln!(j, "  \"proof_a\": \"{}\",", hex::encode(ep.a)).unwrap();
    writeln!(j, "  \"proof_b\": \"{}\",", hex::encode(ep.b)).unwrap();
    writeln!(j, "  \"proof_c\": \"{}\"\n", hex::encode(ep.c)).unwrap();
    j.push_str("}\n");
    fs::write("artifacts/demo_proof.json", j).unwrap();
    println!("wrote artifacts/demo_proof.json");
}
